#!/usr/bin/expect
exp_internal 1
set -Eeuo pipefail
set timeout 5

spawn git pull --no-progress origin main

expect {
  "*(yes/no)? " {
    send "yes\n"
    exp_continue
  }
  "*Enter passphrase for key '/home/robery/.ssh/id_ed25519': " {
    send "\n"
  }
  "*Already up to date.*" {
    exit 0
  }
  "*Fast-forward*" {
    exit 0
  }
}
expect eof

lassign [wait] pid spawn_id os_error_flag exit_status
exit $exit_status
